Repository projectdiscovery/subfinder, pull requests merged in 2020-07, with the labels that each got.

#255 Added GitHub search source
  config.yaml
  go.mod
  go.sum
  pkg/passive/sources.go
  pkg/runner/config.go
  pkg/subscraping/sources/github/github.go
  pkg/subscraping/types.go
Labels: enhancement

#261 using ld compiler
  .github/workflows/release.yml
Labels: bug

#267 Handle GitHub Search API rate limit exceeded
  pkg/runner/config.go
  pkg/subscraping/sources/github/github.go
  pkg/subscraping/sources/github/tokenmanager.go
  pkg/subscraping/types.go
Labels: Status: Completed
