Repository projectdiscovery/subfinder, pull requests merged in 2020-09, with the labels that each got.

#303 recon.dev: fix token
  README.md
  pkg/runner/config.go
  pkg/subscraping/sources/recon/recon.go
  pkg/subscraping/types.go
Labels: Status: Accepted

#323 fdmax => autofdmax + silent fail
  cmd/subfinder/main.go
Labels: Status: Review Needed, Type: Enhancement

#332 small changes
  Dockerfile
  v2/go.mod
  v2/go.sum
Labels: Type: Bug
