Repository projectdiscovery/subfinder, pull requests merged in 2021-08, with the labels that each got.

#438 dnsdumpster is not working. The bug has been fixed.
  v2/pkg/subscraping/sources/dnsdumpster/dnsdumpster.go
Labels: Type: Bug

#420 Add fofa for SubFinder
  v2/pkg/passive/sources.go
  v2/pkg/runner/config.go
  v2/pkg/subscraping/sources/fofa/fofa.go
  v2/pkg/subscraping/types.go
Labels: Status: Completed

#445 Retrieve archiveis first page
  v2/pkg/subscraping/sources/archiveis/archiveis.go
Labels: status:pending review 🔬
