Repository projectdiscovery/subfinder, pull requests merged in 2021-02, with the labels that each got.

#370 build fix
  .github/workflows/build.yaml
Labels: Status: In Progress

#371 Fixed shodan module in order to correctly reflect all results
  DISCLAIMER.md
  Dockerfile
  LICENSE.md
  README.md
  v2/pkg/resolve/resolve.go
  v2/pkg/subscraping/sources/shodan/shodan.go
Labels: Status: Accepted

#377 Removing deprecated cebaidu
  v2/pkg/passive/sources.go
  v2/pkg/subscraping/sources/cebaidu/cebaidu.go
Labels: Status: Completed, Type: Bug

#376 Removing deprecated certspotterold
  v2/pkg/passive/sources.go
  v2/pkg/subscraping/sources/certspotterold/certspotterold.go
Labels: Status: Review Needed, Type: Bug

#375 passive total fix
  v2/pkg/subscraping/sources/passivetotal/passivetotal.go
Labels: Priority: Low, Status: Review Needed

#374 Deps update
  .github/dependabot.yml
  .golangci.yml
  v2/cmd/subfinder/main.go
  v2/go.mod
  v2/go.sum
  v2/pkg/passive/passive.go
  v2/pkg/runner/banners.go
  v2/pkg/runner/chaosuploader.go
  v2/pkg/runner/enumerate.go
  v2/pkg/runner/options.go
  v2/pkg/runner/validate.go
  v2/pkg/subscraping/agent.go
  v2/pkg/subscraping/sources/github/github.go
Labels: Type: Maintenance

#381 Removing chaos upload
  README.md
  v2/pkg/runner/chaosuploader.go
  v2/pkg/runner/enumerate.go
  v2/pkg/runner/options.go
  v2/pkg/runner/outputter.go
Labels: Priority: Low, Type: Maintenance

#355 dns => dnsx
  .github/workflows/build.yaml
  .github/workflows/release.yml
  Dockerfile
  v2/go.mod
  v2/go.sum
  v2/pkg/passive/passive.go
  v2/pkg/passive/sources.go
  v2/pkg/resolve/client.go
  v2/pkg/resolve/resolve.go
  v2/pkg/runner/enumerate.go
  v2/pkg/runner/initialize.go
  v2/pkg/runner/util.go
  v2/pkg/subscraping/sources/github/github.go
  v2/pkg/subscraping/sources/ximcx/ximcx.go
Labels: Status: Revision Needed, Type: Enhancement

#383 Dev goling less strict
  .golangci.yml
  v2/go.mod
  v2/pkg/resolve/resolve.go
  v2/pkg/runner/outputter.go
  v2/pkg/subscraping/doc.go
  v2/pkg/subscraping/sources/alienvault/alienvault.go
  v2/pkg/subscraping/sources/anubis/anubis.go
  v2/pkg/subscraping/sources/binaryedge/binaryedge.go
  v2/pkg/subscraping/sources/censys/censys.go
  v2/pkg/subscraping/sources/certspotter/certspotter.go
  v2/pkg/subscraping/sources/chaos/chaos.go
  v2/pkg/subscraping/sources/commoncrawl/commoncrawl.go
  v2/pkg/subscraping/sources/crtsh/crtsh.go
  v2/pkg/subscraping/sources/dnsdb/dnsdb.go
  v2/pkg/subscraping/sources/dnsdumpster/dnsdumpster.go
  v2/pkg/subscraping/sources/hackertarget/hackertarget.go
  v2/pkg/subscraping/sources/intelx/intelx.go
  v2/pkg/subscraping/sources/passivetotal/passivetotal.go
  v2/pkg/subscraping/sources/recon/recon.go
  v2/pkg/subscraping/sources/riddler/riddler.go
  v2/pkg/subscraping/sources/robtex/robtext.go
  v2/pkg/subscraping/sources/securitytrails/securitytrails.go
  v2/pkg/subscraping/sources/shodan/shodan.go
  v2/pkg/subscraping/sources/sitedossier/sitedossier.go
  v2/pkg/subscraping/sources/sonarsearch/sonarsearch.go
  v2/pkg/subscraping/sources/spyse/spyse.go
  v2/pkg/subscraping/sources/sublist3r/subllist3r.go
  v2/pkg/subscraping/sources/threatbook/threatbook.go
  v2/pkg/subscraping/sources/threatcrowd/threatcrowd.go
  v2/pkg/subscraping/sources/threatminer/threatminer.go
  v2/pkg/subscraping/sources/virustotal/virustotal.go
  v2/pkg/subscraping/sources/waybackarchive/waybackarchive.go
  v2/pkg/subscraping/sources/zoomeye/zoomeye.go
Labels: Type: Maintenance

#385 updating gologger version
  v2/go.mod
  v2/go.sum
  v2/pkg/passive/passive.go
  v2/pkg/runner/enumerate.go
  v2/pkg/subscraping/sources/github/github.go
Labels: Type: Maintenance

#386 fixing dockerfile
  Dockerfile
Labels: Type: Bug

#387 [Subfinder 2.4.6] dev => master
  .github/dependabot.yml
  .github/workflows/build.yaml
  .github/workflows/release.yml
  .golangci.yml
  Dockerfile
  README.md
  v2/cmd/subfinder/main.go
  v2/go.mod
  v2/go.sum
  v2/pkg/passive/passive.go
  v2/pkg/passive/sources.go
  v2/pkg/resolve/client.go
  v2/pkg/resolve/resolve.go
  v2/pkg/runner/banners.go
  v2/pkg/runner/chaosuploader.go
  v2/pkg/runner/enumerate.go
  v2/pkg/runner/initialize.go
  v2/pkg/runner/options.go
  v2/pkg/runner/outputter.go
  v2/pkg/runner/util.go
  v2/pkg/runner/validate.go
  v2/pkg/subscraping/agent.go
  v2/pkg/subscraping/doc.go
  v2/pkg/subscraping/sources/alienvault/alienvault.go
  v2/pkg/subscraping/sources/anubis/anubis.go
  v2/pkg/subscraping/sources/binaryedge/binaryedge.go
  v2/pkg/subscraping/sources/cebaidu/cebaidu.go
  v2/pkg/subscraping/sources/censys/censys.go
  v2/pkg/subscraping/sources/certspotter/certspotter.go
  v2/pkg/subscraping/sources/certspotterold/certspotterold.go
  v2/pkg/subscraping/sources/chaos/chaos.go
  v2/pkg/subscraping/sources/commoncrawl/commoncrawl.go
  v2/pkg/subscraping/sources/crtsh/crtsh.go
  v2/pkg/subscraping/sources/dnsdb/dnsdb.go
  v2/pkg/subscraping/sources/dnsdumpster/dnsdumpster.go
  v2/pkg/subscraping/sources/github/github.go
  v2/pkg/subscraping/sources/hackertarget/hackertarget.go
  v2/pkg/subscraping/sources/intelx/intelx.go
  v2/pkg/subscraping/sources/ipv4info/ipv4info.go
  v2/pkg/subscraping/sources/passivetotal/passivetotal.go
  v2/pkg/subscraping/sources/recon/recon.go
  v2/pkg/subscraping/sources/riddler/riddler.go
  v2/pkg/subscraping/sources/robtex/robtext.go
  v2/pkg/subscraping/sources/securitytrails/securitytrails.go
  v2/pkg/subscraping/sources/shodan/shodan.go
  v2/pkg/subscraping/sources/sitedossier/sitedossier.go
  v2/pkg/subscraping/sources/sonarsearch/sonarsearch.go
  v2/pkg/subscraping/sources/spyse/spyse.go
  v2/pkg/subscraping/sources/sublist3r/subllist3r.go
  v2/pkg/subscraping/sources/threatbook/threatbook.go
  v2/pkg/subscraping/sources/threatcrowd/threatcrowd.go
  v2/pkg/subscraping/sources/threatminer/threatminer.go
  v2/pkg/subscraping/sources/virustotal/virustotal.go
  v2/pkg/subscraping/sources/waybackarchive/waybackarchive.go
  v2/pkg/subscraping/sources/ximcx/ximcx.go
  v2/pkg/subscraping/sources/zoomeye/zoomeye.go
Labels: Status: Review Needed, Type: Enhancement

#394 fixing resolver missing port
  v2/pkg/runner/initialize.go
Labels: Type: Bug

#397 Improved Github subdomain matching regex
  v2/pkg/subscraping/sources/github/github.go
Labels: Status: Accepted
