Repository projectdiscovery/subfinder, pull requests merged in 2022-11, with the labels that each got.

#679 Adding recon.cloud source
  README.md
  v2/pkg/passive/sources.go
  v2/pkg/passive/sources_test.go
  v2/pkg/subscraping/sources/reconcloud/reconcloud.go
Labels: Type: Enhancement

#680 Adding hunter source
  README.md
  v2/pkg/passive/sources.go
  v2/pkg/passive/sources_test.go
  v2/pkg/subscraping/sources/hunter/hunter.go
Labels: Type: Enhancement

#699 Add callback function
  README.md
  v2/pkg/runner/enumerate.go
  v2/pkg/runner/options.go
Labels: Status: Review Needed

#700 Fixed crt.sh SQL query
  v2/pkg/subscraping/sources/crtsh/crtsh.go
Labels: Type: Bug

#720 resolve failing cases
  .github/workflows/build-test.yml
  .github/workflows/lint-test.yml
  v2/pkg/passive/sources.go
  v2/pkg/passive/sources_test.go
  v2/pkg/passive/sources_wo_auth_test.go
  v2/pkg/subscraping/agent.go
  v2/pkg/subscraping/sources/crtsh/crtsh.go
Labels: Status: In Progress
