Repository projectdiscovery/subfinder, pull requests merged in 2022-02, with the labels that each got.

#495 Improving input items sanitization
  v2/pkg/runner/options.go
  v2/pkg/runner/runner.go
  v2/pkg/runner/util.go
Labels: Status: Review Needed, Type: Bug

#497 Updating GH workflows + sonar
  .github/dependabot.yml
  .github/workflows/build-test.yml
  .github/workflows/release-binary.yml
  .github/workflows/sonarcloud.yml
  sonar-project.properties
Labels: Status: Review Needed, Type: Maintenance

#499 Fixing typo in code comment
  v2/pkg/subscraping/types.go
Labels: Type: Maintenance

#498 goflags support
  README.md
  v2/go.mod
  v2/go.sum
  v2/pkg/passive/passive.go
  v2/pkg/passive/sources.go
  v2/pkg/runner/banners.go
  v2/pkg/runner/config.go
  v2/pkg/runner/enumerate.go
  v2/pkg/runner/initialize.go
  v2/pkg/runner/options.go
  v2/pkg/runner/runner.go
  v2/pkg/runner/util.go
  v2/pkg/runner/validate.go
  v2/pkg/subscraping/agent.go
Labels: Status: Review Needed, Type: Enhancement
